services:
  icecast:
    image: moul/icecast
    ports:
      - "8000:8000"
    environment:
      ICECAST_SOURCE_PASSWORD: password
      ICECAST_PASSWORD: password
      ICECAST_ADMIN_PASSWORD: admin
      ICECAST_RELAY_PASSWORD: relay
    restart: unless-stopped